"""empty message

Revision ID: 091db760863b
Revises: 46540ba12e6d
Create Date: 2024-12-07 13:23:44.563309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '091db760863b'
down_revision = '46540ba12e6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('species',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('height',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('height',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('species',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
